Begin writing nuke components for builds

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,27 +31,27 @@ jobs:
 
       - name: Build Solution
         shell: pwsh
-        run: ./build.ps1 CreateNuGetPackages
+        run: ./build.ps1 Compile
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Unit Tests Checks
-          path: .tests/results/*.trx
-          reporter: dotnet-trx
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: Coverage Report
-          path: .tests/coverage_report/*.*
-
-      - name: Publish the package to GPR
-        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
-        run: dotnet nuget push .artifacts/**/*.nupkg --skip-duplicate -k ${{secrets.GITHUB_TOKEN}}
-
-      - name: Publish the package to nuget.org
-        if: startsWith(github.ref, 'refs/tags/v')
-        run: dotnet nuget push .artifacts/**/*.nupkg --skip-duplicate -k ${{secrets.NUGET_ORG_TOKEN}} -s nuget.org
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: Unit Tests Checks
+#          path: .tests/results/*.trx
+#          reporter: dotnet-trx
+#
+#      - name: Upload Artifact
+#        uses: actions/upload-artifact@v3
+#        if: success() || failure()
+#        with:
+#          name: Coverage Report
+#          path: .tests/coverage_report/*.*
+#
+#      - name: Publish the package to GPR
+#        if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
+#        run: dotnet nuget push .artifacts/**/*.nupkg --skip-duplicate -k ${{secrets.GITHUB_TOKEN}}
+#
+#      - name: Publish the package to nuget.org
+#        if: startsWith(github.ref, 'refs/tags/v')
+#        run: dotnet nuget push .artifacts/**/*.nupkg --skip-duplicate -k ${{secrets.NUGET_ORG_TOKEN}} -s nuget.org
